# Generated by Django 4.0.1 on 2022-01-25 20:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0002_alter_post_author_alter_reply_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reply',
            new_name='Response',
        ),
    ]
